added error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,9 @@ jobs:
 
      - name: Run a sample Github action
        run: echo "This workflow run succesfully for this particular action"
+
+     - name: Simulating error
+       run: echo "error taking place"; exit 1
      
       
     
